### PR TITLE
fix a bunch of typos

### PR DESCRIPTION
**Pull request by fchapoton**
found using codespell

### CODE REVIEW

**Comment by fchapoton** [comment]
could please someone approve the workflow ?

**Comment by fchapoton** [comment]
@fingolfin : would you please approve the workflow ? and merge ?

**Comment by fchapoton** [comment]
nobody out there ? :desert: ?

**Comment by fingolfin** [comment]
I am taking care of about 100 GAP packages mostly alone. I don't get around to all of them all the time. So yeah in this sense, nobody is here. Not sure what the hurry is, though? These are just harmless typo fixes. Before any new release of any given package, like this one, I'd check for any open PRs and merge them if needed

**Comment by fchapoton** [comment]
Ok, I understand and apologize for showing signs of impatience. I thought that GAP had more funding than sage and more people to help. Too many things are depending on too few people.

**Pull request merged**
